networks:
- name: Goerli
  networks:
    - name: Testnet
      chainid: 5
      id: goerli-test
      host: https://goerli.infura.io/v3/YOUR-PROJECT-ID
      explorer: https://goerli.etherscan.io/api

- name: BNB Chain
  networks:
    - name: Testnet
      chainid: 97
      id: bnb-test
      host: https://data-seed-prebnb-1-s1.binance.org:8545
      explorer: https://testnet.bscscan.com/api

- name: Avalanche
  networks:
    - name: Testnet
      chainid: 43113
      id: avalanche-fuji
      host: https://api.avax-test.network/ext/bc/C/rpc
      explorer: https://cchain.explorer.avax-test.network/api

- name: Fantom
  networks:
    - name: Testnet
      chainid: 4002
      id: fantom-test
      host: https://rpc.testnet.fantom.network
      explorer: https://explorer.testnet.fantom.network/api

- name: Celo
  networks:
    - name: Testnet
      chainid: 44787
      id: celo-alfajores
      host: https://alfajores-forno.celo-testnet.org
      explorer: https://alfajores-blockscout.celo-testnet.org/api

- name: Cronos
  networks:
    - name: Testnet
      chainid: 338
      id: cronos-test
      host: https://cronos-testnet.crypto.org:8545
      explorer: https://cronos-explorer.crypto.org/api